FROM openjdk:21-jdk

COPY target/market-data-api-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "market-data-api-0.0.1-SNAPSHOT.jar"]
git config --global user.email "raminduanjana22171@gmail.com"
git config --global user.name "RaminduA"
